"""Single source of truth for dashboard environment settings."""

from __future__ import annotations

from typing import Any


def _as_bool(value: Any) -> bool:
    return str(value).lower() in ("1", "true", "yes", "on")

ENV_FIELDS = [{'key': 'KIS_REAL_CHECK_ENABLED',
  'label': 'KIS real_check Enabled',
  'type': 'bool',
  'hint': 'Use real KIS API for market-data checks only; balance and orders keep using the execution account.',
  'options': [],
  'secret': False,
  'restart_required': False},
 {'key': 'KIS_REAL_CHECK_APP_KEY', 'label': 'KIS real_check App Key', 'type': 'secret', 'hint': '', 'options': [], 'secret': True, 'restart_required': False},
 {'key': 'KIS_REAL_CHECK_APP_SECRET',
  'label': 'KIS real_check App Secret',
  'type': 'secret',
  'hint': '',
  'options': [],
  'secret': True,
  'restart_required': False},
 {'key': 'KIS_REAL_CHECK_ACCOUNT', 'label': 'KIS real_check Account', 'type': 'text', 'hint': '', 'options': [], 'secret': False, 'restart_required': False},
 {'key': 'KIS_REAL_CHECK_HTS_ID', 'label': 'KIS real_check HTS ID', 'type': 'text', 'hint': '', 'options': [], 'secret': False, 'restart_required': False},
 {'key': 'KIS_REAL_CHECK_CONDITION_SEARCH_ENABLED',
  'label': 'KIS real_check Condition Enabled',
  'type': 'bool',
  'hint': '',
  'options': [],
  'secret': False,
  'restart_required': False},
 {'key': 'KIS_REAL_CHECK_CONDITION_USER_ID',
  'label': 'KIS real_check Condition User ID',
  'type': 'text',
  'hint': '',
  'options': [],
  'secret': False,
  'restart_required': False},
 {'key': 'KIS_REAL_CHECK_CONDITION_SEQ',
  'label': 'KIS real_check Condition Seq',
  'type': 'text',
  'hint': '',
  'options': [],
  'secret': False,
  'restart_required': False},
 {'key': 'KIS_REAL_CHECK_CONDITION_NAME',
  'label': 'KIS real_check Condition Name',
  'type': 'text',
  'hint': '',
  'options': [],
  'secret': False,
  'restart_required': False},
 {'key': 'KISTOCK_APP_KEY', 'label': 'KIS App Key', 'type': 'secret', 'hint': '국내주식 KIS API 앱 키입니다.', 'options': [], 'secret': True, 'restart_required': True},
 {'key': 'KISTOCK_APP_SECRET',
  'label': 'KIS App Secret',
  'type': 'secret',
  'hint': '국내주식 KIS API 앱 시크릿입니다.',
  'options': [],
  'secret': True,
  'restart_required': True},
 {'key': 'KISTOCK_ACCOUNT', 'label': 'KIS 계좌번호', 'type': 'text', 'hint': '8자리 또는 10자리 계좌번호를 입력합니다.', 'options': [], 'secret': False, 'restart_required': True},
 {'key': 'KISTOCK_HTS_ID',
  'label': 'KIS HTS ID',
  'type': 'text',
  'hint': '실시간 주문체결 통보와 조건검색식 조회에 사용할 HTS ID입니다.',
  'options': [],
  'secret': False,
  'restart_required': False},
 {'key': 'KIS_WEBSOCKET_ENABLED',
  'label': 'KIS 웹소켓 사용',
  'type': 'bool',
  'hint': 'true이면 KIS 실시간 체결통보 웹소켓을 시작할 수 있습니다.',
  'options': [],
  'secret': False,
  'restart_required': False},
 {'key': 'KIS_CONDITION_SEARCH_ENABLED',
  'label': 'KIS 조건검색 사용',
  'type': 'bool',
  'hint': 'true이면 매수 후보 스캔에 조건검색식 결과를 우선 반영합니다.',
  'options': [],
  'secret': False,
  'restart_required': False},
 {'key': 'KIS_CONDITION_USER_ID',
  'label': '조건검색 사용자 ID',
  'type': 'text',
  'hint': '비워두면 KIS HTS ID를 사용합니다.',
  'options': [],
  'secret': False,
  'restart_required': False},
 {'key': 'KIS_CONDITION_SEQ',
  'label': '조건검색식 번호',
  'type': 'text',
  'hint': 'HTS에 저장된 조건검색식 일련번호입니다.',
  'options': [],
  'secret': False,
  'restart_required': False},
 {'key': 'KIS_CONDITION_NAME', 'label': '조건검색식 이름', 'type': 'text', 'hint': 'HTS에 저장된 조건검색식 이름입니다.', 'options': [], 'secret': False, 'restart_required': False},
 {'key': 'TRADING_ENV',
  'label': '거래 환경',
  'type': 'select',
  'options': ['demo', 'real'],
  'hint': 'demo=모의투자, real=실전투자 환경입니다.',
  'secret': False,
  'restart_required': True},
 {'key': 'DRY_RUN', 'label': '주문 차단 모드', 'type': 'bool', 'hint': 'true이면 실제 KIS 주문 API를 호출하지 않습니다.', 'options': [], 'secret': False, 'restart_required': True},
 {'key': 'ENABLE_LIVE_TRADING',
  'label': '실전 주문 허용',
  'type': 'bool',
  'hint': '실전 환경에서 실제 주문을 허용하는 최종 보호 스위치입니다.',
  'options': [],
  'secret': False,
  'restart_required': True},
 {'key': 'REQUIRE_APPROVAL',
  'label': '주문 승인 필요',
  'type': 'bool',
  'hint': 'true이면 주문을 승인 대기열에 먼저 등록합니다.',
  'options': [],
  'secret': False,
  'restart_required': True},
 {'key': 'ONLINE_ACCESS_BLOCKED',
  'label': '온라인 접속 차단',
  'type': 'bool',
  'hint': 'true이면 외부 API, 웹소켓, 시세 갱신과 모든 주문 실행을 차단합니다. DB 저장 정보는 계속 표시됩니다.',
  'options': [],
  'secret': False,
  'restart_required': True},
 {'key': 'SPLIT_N', 'label': '분할 매수 횟수', 'type': 'int', 'hint': '', 'options': [], 'secret': False, 'restart_required': False},
 {'key': 'STOP_LOSS_PCT', 'label': '손절 기준 %', 'type': 'float', 'hint': '', 'options': [], 'secret': False, 'restart_required': False},
 {'key': 'TAKE_PROFIT', 'label': '익절 기준 %', 'type': 'float', 'hint': '', 'options': [], 'secret': False, 'restart_required': False},
 {'key': 'RSI_BUY', 'label': 'RSI 매수 기준', 'type': 'int', 'hint': '', 'options': [], 'secret': False, 'restart_required': False},
 {'key': 'RSI_SELL', 'label': 'RSI 매도 기준', 'type': 'int', 'hint': '', 'options': [], 'secret': False, 'restart_required': False},
 {'key': 'TRAILING_STOP_ACTIVATION_PCT', 'label': '트레일링 활성 수익률 %', 'type': 'float', 'hint': '', 'options': [], 'secret': False, 'restart_required': False},
 {'key': 'TRAILING_STOP_PCT', 'label': '고점 대비 청산 하락률 %', 'type': 'float', 'hint': '', 'options': [], 'secret': False, 'restart_required': False},
 {'key': 'TRAILING_STOP_LOOKBACK', 'label': '트레일링 참고 기간', 'type': 'int', 'hint': '', 'options': [], 'secret': False, 'restart_required': False},
 {'key': 'TRADE_VALUE_SURGE_RATIO',
  'label': '거래대금 급등 배수',
  'type': 'float',
  'hint': '당일 거래대금이 직전 20일 평균의 몇 배 이상일 때 가점할지 설정합니다.',
  'options': [],
  'secret': False,
  'restart_required': False},
 {'key': 'FIRST_WAVE_MIN_PCT', 'label': '1차 파동 최소 상승률 %', 'type': 'float', 'hint': '', 'options': [], 'secret': False, 'restart_required': False},
 {'key': 'FIRST_WAVE_PULLBACK_MIN_PCT', 'label': '눌림목 최소 조정률 %', 'type': 'float', 'hint': '', 'options': [], 'secret': False, 'restart_required': False},
 {'key': 'FIRST_WAVE_PULLBACK_MAX_PCT', 'label': '눌림목 최대 조정률 %', 'type': 'float', 'hint': '', 'options': [], 'secret': False, 'restart_required': False},
 {'key': 'TOTAL_CAPITAL', 'label': '총 운용 자금', 'type': 'float', 'hint': '', 'options': [], 'secret': False, 'restart_required': False},
 {'key': 'ACCOUNT_INITIAL_CAPITAL',
  'label': '계좌 초기자산',
  'type': 'float',
  'hint': '총자산 대비 전체 손익을 계산하는 표시 기준이며 주문 규모에는 영향을 주지 않습니다.',
  'options': [],
  'secret': False,
  'restart_required': True},
 {'key': 'MAX_POSITIONS', 'label': '최대 보유 종목 수', 'type': 'int', 'hint': '', 'options': [], 'secret': False, 'restart_required': False},
 {'key': 'MAX_SINGLE_WEIGHT', 'label': '종목당 최대 비중', 'type': 'float', 'hint': '', 'options': [], 'secret': False, 'restart_required': False},
 {'key': 'CASH_BUFFER', 'label': '현금 보유 비중', 'type': 'float', 'hint': '', 'options': [], 'secret': False, 'restart_required': False},
 {'key': 'MAX_DAILY_LOSS_PCT', 'label': '일 최대 손실 %', 'type': 'float', 'hint': '', 'options': [], 'secret': False, 'restart_required': False},
 {'key': 'HANSTOCK_EXCLUDED_SYMBOLS',
  'label': 'Hanstock Excluded Symbols',
  'type': 'text',
  'hint': 'Comma-separated domestic stock codes excluded from automated scans and orders.',
  'options': [],
  'secret': False,
  'restart_required': False},
 {'key': 'KIS_ORDER_MIN_INTERVAL_SECONDS',
  'label': 'KIS Order Min Interval Seconds',
  'type': 'float',
  'hint': 'Minimum wait between broker order submissions.',
  'options': [],
  'secret': False,
  'restart_required': True},
 {'key': 'SCAN_UNIVERSE_SIZE', 'label': '스캔 종목 수', 'type': 'int', 'hint': '', 'options': [], 'secret': False, 'restart_required': False},
 {'key': 'KIS_CIRCUIT_COOLDOWN_SECONDS',
  'label': 'KIS API 차단 해제 대기초',
  'type': 'int',
  'hint': 'KIS API 오류가 반복될 때 재시도 전 대기 시간입니다.',
  'options': [],
  'secret': False,
  'restart_required': True},
 {'key': 'TRADE_DB_PATH', 'label': '거래 DB 경로', 'type': 'text', 'hint': '', 'options': [], 'secret': False, 'restart_required': True},
 {'key': 'ACTIVE_MODEL_VERSION', 'label': '활성 모델 버전', 'type': 'text', 'hint': '', 'options': [], 'secret': False, 'restart_required': True},
 {'key': 'AI_STRATEGY_ENABLED',
  'label': 'AI 전략 사용',
  'type': 'bool',
  'hint': 'true이면 후보 평가에 OpenAI 모델 점수를 함께 사용합니다.',
  'options': [],
  'secret': False,
  'restart_required': False},
 {'key': 'AI_SCORE_WEIGHT',
  'label': 'AI 점수 반영 비중',
  'type': 'float',
  'hint': '0~1 사이 값입니다. 0.4이면 룰 60%, AI 40%로 계산합니다.',
  'options': [],
  'secret': False,
  'restart_required': False},
 {'key': 'AI_MIN_MODEL_CONFIDENCE', 'label': 'AI 최소 신뢰도', 'type': 'float', 'hint': '', 'options': [], 'secret': False, 'restart_required': False},
 {'key': 'AI_REQUIRE_BACKTEST_PASS', 'label': '백테스트 통과 필수', 'type': 'bool', 'hint': '', 'options': [], 'secret': False, 'restart_required': False},
 {'key': 'AI_AUTO_APPROVE', 'label': 'AI 자동 승인', 'type': 'bool', 'hint': '', 'options': [], 'secret': False, 'restart_required': False},
 {'key': 'AI_MIN_RULE_SCORE',
  'label': 'AI 최소 룰 점수',
  'type': 'float',
  'hint': 'OpenAI 호출 전 필터링할 최소 룰 점수입니다 (기본 1.5).',
  'options': [],
  'secret': False,
  'restart_required': True},
 {'key': 'AI_ALLOW_CANDIDATE_PROMOTION',
  'label': 'AI 후보 승격 허용',
  'type': 'bool',
  'hint': 'true이면 룰 미달 종목도 AI 점수를 바탕으로 승급합니다.',
  'options': [],
  'secret': False,
  'restart_required': True},
 {'key': 'OPENAI_API_KEY',
  'label': 'OpenAI API Key',
  'type': 'secret',
  'hint': 'gpt-5-mini 호출에 사용할 OpenAI API 키입니다.',
  'options': [],
  'secret': True,
  'restart_required': False},
 {'key': 'OPENAI_MODEL', 'label': 'OpenAI 모델', 'type': 'text', 'hint': '예: gpt-5-mini', 'options': [], 'secret': False, 'restart_required': False},
 {'key': 'OPENAI_TIMEOUT_SECONDS', 'label': 'OpenAI 응답 제한초', 'type': 'float', 'hint': '', 'options': [], 'secret': False, 'restart_required': False},
 {'key': 'AI_CANDIDATE_LIMIT', 'label': 'AI 평가 후보 수', 'type': 'int', 'hint': '', 'options': [], 'secret': False, 'restart_required': False},
 {'key': 'SLACK_WEBHOOK_URL', 'label': 'Slack Webhook URL', 'type': 'secret', 'hint': '', 'options': [], 'secret': True, 'restart_required': True},
 {'key': 'MISTOCK_SLACK_WEBHOOK_URL',
  'label': 'Mistock Slack Webhook URL',
  'type': 'secret',
  'hint': '',
  'options': [],
  'secret': True,
  'restart_required': True},
 {'key': 'TELEGRAM_API_ID', 'label': 'Telegram API ID', 'type': 'secret', 'hint': '', 'options': [], 'secret': True, 'restart_required': True},
 {'key': 'TELEGRAM_API_HASH', 'label': 'Telegram API Hash', 'type': 'secret', 'hint': '', 'options': [], 'secret': True, 'restart_required': True},
 {'key': 'TELEGRAM_SESSION_NAME',
  'label': 'Telegram Session Name',
  'type': 'text',
  'hint': '로컬 Telethon 세션 경로입니다. Git에 포함하지 마세요.',
  'options': [],
  'secret': False,
  'restart_required': True},
 {'key': 'TELEGRAM_TARGET_CHANNELS',
  'label': 'Telegram Target Channels',
  'type': 'text',
  'hint': '쉼표로 구분한 채널 사용자명, ID, 초대 링크입니다.',
  'options': [],
  'secret': False,
  'restart_required': True},
 {'key': 'MISTOCK_EXCHANGE_MAP',
  'label': '미국주식 거래소 매핑',
  'type': 'text',
  'hint': '예: BRK.B=NYSE,TSLA=NASD',
  'options': [],
  'secret': False,
  'restart_required': True},
 {'key': 'MISTOCK_CURRENCY',
  'label': 'Mistock Currency',
  'type': 'text',
  'hint': '미스톡 대시보드 표기 통화입니다. 예: USD, KRW',
  'options': [],
  'secret': False,
  'restart_required': True},
 {'key': 'MISTOCK_MARKET',
  'label': 'Mistock Market',
  'type': 'text',
  'hint': '미국주식 타겟 시장입니다. 예: NASDAQ',
  'options': [],
  'secret': False,
  'restart_required': True},
 {'key': 'MISTOCK_TRADING_ENV',
  'label': 'Mistock Trading Env',
  'type': 'select',
  'options': ['paper', 'demo', 'real'],
  'hint': 'paper=가상모의, demo=실제모의, real=실전매매',
  'secret': False,
  'restart_required': True},
 {'key': 'MISTOCK_DRY_RUN',
  'label': 'Mistock Dry Run (주문차단)',
  'type': 'bool',
  'hint': 'true이면 실제 KIS 미국주식 주문 API를 호출하지 않습니다.',
  'options': [],
  'secret': False,
  'restart_required': True},
 {'key': 'MISTOCK_ENABLE_LIVE_TRADING',
  'label': 'Mistock Enable Live Trading',
  'type': 'bool',
  'hint': '미국주식 실전매매 최종허용 안전스위치입니다.',
  'options': [],
  'secret': False,
  'restart_required': True},
 {'key': 'MISTOCK_REQUIRE_APPROVAL',
  'label': 'Mistock Require Approval',
  'type': 'bool',
  'hint': 'true이면 미국주식 주문 시 승인 대기를 거칩니다.',
  'options': [],
  'secret': False,
  'restart_required': True},
 {'key': 'MISTOCK_TOTAL_CAPITAL',
  'label': 'Mistock Total Capital',
  'type': 'float',
  'hint': '미국주식 총 운용 자금입니다. 단위는 MISTOCK_CURRENCY 값을 따릅니다.',
  'options': [],
  'secret': False,
  'restart_required': True},
 {'key': 'MISTOCK_TRADE_DB_PATH',
  'label': 'Mistock Trade DB Path',
  'type': 'text',
  'hint': '미국주식 거래 기록용 SQLite DB 경로입니다.',
  'options': [],
  'secret': False,
  'restart_required': True},
 {'key': 'USDKRW_FALLBACK_RATE',
  'label': 'USD/KRW Fallback Rate',
  'type': 'float',
  'hint': 'yfinance 환율 수집 실패 시 사용할 고정/기본 환율입니다. 기본값: 1380.0',
  'options': [],
  'secret': False,
  'restart_required': True},
 {'key': 'MISTOCK_UNIVERSE',
  'label': '미스톡 기본 스캔 유니버스',
  'type': 'text',
  'hint': '미국주식 스캔 시 사용할 기본 관심종목 목록(쉼표 구분)입니다. 예: AAPL,MSFT,NVDA,TSLA',
  'options': [],
  'secret': False,
  'restart_required': True}]

STRATEGY_ENV_BINDINGS = {
    "SPLIT_N": ("split_n", "SPLIT_N", int),
    "STOP_LOSS_PCT": ("stop_loss_pct", "STOP_LOSS_PCT", float),
    "TAKE_PROFIT": ("take_profit", "TAKE_PROFIT", float),
    "RSI_BUY": ("rsi_buy", "RSI_BUY", int),
    "RSI_SELL": ("rsi_sell", "RSI_SELL", int),
    "TRAILING_STOP_ACTIVATION_PCT": ("trailing_stop_activation_pct", None, float),
    "TRAILING_STOP_PCT": ("trailing_stop_pct", None, float),
    "TRAILING_STOP_LOOKBACK": ("trailing_stop_lookback", None, int),
    "TRADE_VALUE_SURGE_RATIO": ("trade_value_surge_ratio", None, float),
    "FIRST_WAVE_MIN_PCT": ("first_wave_min_pct", None, float),
    "FIRST_WAVE_PULLBACK_MIN_PCT": ("first_wave_pullback_min_pct", None, float),
    "FIRST_WAVE_PULLBACK_MAX_PCT": ("first_wave_pullback_max_pct", None, float),
    "TOTAL_CAPITAL": ("total_capital", "TOTAL_CAPITAL", float),
    "MAX_POSITIONS": ("max_positions", "MAX_POSITIONS", int),
    "MAX_SINGLE_WEIGHT": ("max_single_weight", "MAX_SINGLE_WEIGHT", float),
    "CASH_BUFFER": ("cash_buffer", "CASH_BUFFER", float),
    "MAX_DAILY_LOSS_PCT": ("max_daily_loss_pct", "MAX_DAILY_LOSS_PCT", float),
    "HANSTOCK_EXCLUDED_SYMBOLS": ("hanstock_excluded_symbols", None, str),
    "SCAN_UNIVERSE_SIZE": ("scan_universe_size", "SCAN_UNIVERSE_SIZE", int),
}

AI_ENV_BINDINGS = {
    "AI_STRATEGY_ENABLED": ("ai_strategy_enabled", _as_bool),
    "AI_SCORE_WEIGHT": ("ai_score_weight", float),
    "AI_MIN_MODEL_CONFIDENCE": ("ai_min_model_confidence", float),
    "AI_REQUIRE_BACKTEST_PASS": ("ai_require_backtest_pass", _as_bool),
    "AI_AUTO_APPROVE": ("ai_auto_approve", _as_bool),
    "OPENAI_API_KEY": ("openai_api_key", str),
    "OPENAI_MODEL": ("openai_model", str),
    "OPENAI_TIMEOUT_SECONDS": ("openai_timeout_seconds", float),
    "AI_CANDIDATE_LIMIT": ("ai_candidate_limit", int),
}

KIS_ENV_BINDINGS = {
    "KISTOCK_HTS_ID": ("kistock_hts_id", str),
    "KIS_WEBSOCKET_ENABLED": ("kis_websocket_enabled", _as_bool),
    "KIS_CONDITION_SEARCH_ENABLED": ("kis_condition_search_enabled", _as_bool),
    "KIS_CONDITION_USER_ID": ("kis_condition_user_id", str),
    "KIS_CONDITION_SEQ": ("kis_condition_seq", str),
    "KIS_CONDITION_NAME": ("kis_condition_name", str),
    "KIS_REAL_CHECK_ENABLED": ("kis_real_check_enabled", _as_bool),
    "KIS_REAL_CHECK_APP_KEY": ("kis_real_check_app_key", str),
    "KIS_REAL_CHECK_APP_SECRET": ("kis_real_check_app_secret", str),
    "KIS_REAL_CHECK_ACCOUNT": ("kis_real_check_account", str),
    "KIS_REAL_CHECK_HTS_ID": ("kis_real_check_hts_id", str),
    "KIS_REAL_CHECK_CONDITION_SEARCH_ENABLED": ("kis_real_check_condition_search_enabled", _as_bool),
    "KIS_REAL_CHECK_CONDITION_USER_ID": ("kis_real_check_condition_user_id", str),
    "KIS_REAL_CHECK_CONDITION_SEQ": ("kis_real_check_condition_seq", str),
    "KIS_REAL_CHECK_CONDITION_NAME": ("kis_real_check_condition_name", str),
}


for _field in ENV_FIELDS:
    _field["runtime_binding"] = (
        STRATEGY_ENV_BINDINGS.get(_field["key"])
        or AI_ENV_BINDINGS.get(_field["key"])
        or KIS_ENV_BINDINGS.get(_field["key"])
    )

ENV_FIELD_MAP = {field["key"]: field for field in ENV_FIELDS}
